window.__frontlineBoot = 'modules loaded';
const canvas=document.querySelector('#game'),renderer=new THREE.WebGLRenderer({canvas,antialias:true});
window.__frontlineBoot = 'renderer created';
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color('#94abb8');scene.fog=new THREE.Fog('#94abb8',28,155);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.08,240);camera.rotation.order='YXZ';
const ui={health:document.querySelector('#health'),armor:document.querySelector('#armor'),ammo:document.querySelector('#ammo'),squad:document.querySelector('#squad'),objective:document.querySelector('#objective-text'),clock:document.querySelector('#clock'),stance:document.querySelector('#stance')};
const minimap=document.querySelector('#minimap'),map2d=minimap.getContext('2d');
const clock=new THREE.Clock(),loader=new THREE.GLTFLoader(),ray=new THREE.Raycaster(),keys={};
let started=false,ended=false,paused=false,yaw=0,pitch=0,ammo=30,spare=180,hp=100,armor=70,reload=0,shot=0,crouched=false,elapsed=0,model=null,music=null;
const enemies=[],obstacles=[],traces=[];const V=new THREE.Vector3();
function terrainY(x,z){return Math.sin(x*.055)*1.2+Math.cos(z*.08)*.8+Math.sin((x-z)*.12)*.3;}
function mesh(g,m,x,y,z){const a=new THREE.Mesh(g,m);a.position.set(x,y,z);a.castShadow=a.receiveShadow=true;scene.add(a);return a;}
const grass=new THREE.MeshStandardMaterial({color:'#746d45',roughness:1,flatShading:true}),trunk=new THREE.MeshStandardMaterial({color:'#4a3622',flatShading:true}),leaf=new THREE.MeshStandardMaterial({color:'#3a4c2e',flatShading:true}),wood=new THREE.MeshStandardMaterial({color:'#786545',flatShading:true}),metal=new THREE.MeshStandardMaterial({color:'#3c463d',roughness:.6,metalness:.35,flatShading:true});
function world(){const g=new THREE.PlaneGeometry(230,230,70,70),p=g.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,terrainY(p.getX(i),-p.getY(i)));g.computeVertexNormals();const ground=mesh(g,grass,0,0,0);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;
const sun=new THREE.DirectionalLight('#fff2d2',2.3);sun.position.set(-40,70,28);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=sun.shadow.camera.bottom=-80;sun.shadow.camera.right=sun.shadow.camera.top=80;scene.add(sun);scene.add(new THREE.HemisphereLight('#d7e8ee','#34452d',1.8));
for(let i=0;i<140;i++){let x=((i*37)%190)-95,z=((i*61)%180)-90;if(Math.hypot(x-22,z+18)<22||Math.hypot(x+48,z-46)<12)continue;tree(x,z,.65+(i%5)*.1)}
outpost();radio(22,-18);
}
function tree(x,z,s){const g=new THREE.Group(),y=terrainY(x,z);const t=new THREE.Mesh(new THREE.CylinderGeometry(.12*s,.2*s,2.4*s,6),trunk);t.position.y=1.2*s;g.add(t);for(let i=0;i<3;i++){const c=new THREE.Mesh(new THREE.ConeGeometry((1.1-i*.18)*s,1.7*s,7),leaf);c.position.y=2*s+i*.68*s;c.castShadow=true;g.add(c)}g.position.set(x,y,z);scene.add(g);}
function outpost(){const y=terrainY(22,-18),building=mesh(new THREE.BoxGeometry(14,4,9),new THREE.MeshStandardMaterial({color:'#777267'}),22,y+2,-18);obstacles.push({x:22,z:-18,w:15,d:10});mesh(new THREE.BoxGeometry(15,1,10),new THREE.MeshStandardMaterial({color:'#303631'}),22,y+4.4,-18);for(const [x,z] of [[13,-14],[32,-14],[32,-24]])mesh(new THREE.CylinderGeometry(1.2,1.2,.4,8),wood,x,terrainY(x,z)+.2,z);}
function radio(x,z){const y=terrainY(x,z);for(const sx of [-1,1])for(const sz of [-1,1]){const leg=mesh(new THREE.BoxGeometry(.16,12,.16),metal,x+sx*1.6,y+6,z+sz*1.6);leg.rotation.z=-sx*.12}for(let h=2;h<12;h+=3){mesh(new THREE.BoxGeometry(3.5,.12,.12),metal,x,y+h,z);mesh(new THREE.BoxGeometry(.12,.12,3.5),metal,x,y+h,z)}const l=new THREE.PointLight('#d7e66a',3,18);l.position.set(x,y+13,z);scene.add(l);}
const patrolPositions=[[-48,31],[-39,20],[13,-10],[29,-10],[33,-24]];
function contactTag(){const c=document.createElement('canvas');c.width=256;c.height=72;const x=c.getContext('2d');x.fillStyle='rgba(27,12,8,.86)';x.fillRect(8,8,240,56);x.strokeStyle='#f27554';x.lineWidth=3;x.strokeRect(8,8,240,56);x.fillStyle='#ffe1b1';x.font='bold 24px sans-serif';x.textAlign='center';x.fillText('КОНТАКТ',128,42);const texture=new THREE.CanvasTexture(c);const tag=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,depthWrite:false}));tag.scale.set(3.8,1.05,1);tag.position.y=3.4;return tag;}
function fallbackSoldier(x,z){const g=new THREE.Group(),uniform=new THREE.MeshStandardMaterial({color:'#52694d'}),skin=new THREE.MeshStandardMaterial({color:'#bd9e78'});const body=new THREE.Mesh(new THREE.CylinderGeometry(.34,.42,1.35,7),uniform);body.position.y=1.05;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.25,10,8),skin);head.position.y=1.9;head.castShadow=true;g.add(head);const gun=new THREE.Mesh(new THREE.BoxGeometry(.12,.12,1.1),metal);gun.position.set(.28,1.25,-.35);g.add(gun);g.position.set(x,terrainY(x,z),z);scene.add(g);return g;}
function spawnSoldiers(factory){if(enemies.length)return;patrolPositions.forEach((pos,i)=>{const unit=factory(pos[0],pos[1]);unit.add(contactTag());enemies.push({unit,hp:100,alive:true,cd:.8+i*.22,name:`ПАТРУЛЬ-${i+1}`})});ui.objective.textContent='ОЧИСТИТЕ БЛОКПОСТ';}
function loadSoldier(){loader.load('./assets/swat.glb',gltf=>{model=gltf.scene;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false}});spawnSoldiers((x,z)=>{const unit=THREE.SkeletonUtils.clone(model);unit.scale.setScalar(1.35);unit.position.set(x,terrainY(x,z),z);unit.rotation.y=Math.PI;scene.add(unit);return unit;});},undefined,()=>{spawnSoldiers(fallbackSoldier);ui.objective.textContent='ПАТРУЛЬ ОБНАРУЖЕН';});setTimeout(()=>spawnSoldiers(fallbackSoldier),3500);}
function collide(x,z){return Math.abs(x)>108||Math.abs(z)>108||obstacles.some(o=>Math.abs(x-o.x)<o.w/2+.45&&Math.abs(z-o.z)<o.d/2+.45);}
function startAudio(){if(music)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;music=new A();let i=0,notes=[55,0,65.4,0,49,0,73.4,0];setInterval(()=>{if(ended)return;let f=notes[i++%notes.length];if(!f)return;const o=music.createOscillator(),g=music.createGain();o.frequency.value=f;g.gain.setValueAtTime(.025,music.currentTime);g.gain.exponentialRampToValueAtTime(.001,music.currentTime+.5);o.connect(g).connect(music.destination);o.start();o.stop(music.currentTime+.55)},460);}
function sfx(f,d=.12,v=.09){if(!music)return;const o=music.createOscillator(),g=music.createGain();o.type='square';o.frequency.setValueAtTime(f,music.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,f*.3),music.currentTime+d);g.gain.setValueAtTime(v,music.currentTime);g.gain.exponentialRampToValueAtTime(.001,music.currentTime+d);o.connect(g).connect(music.destination);o.start();o.stop(music.currentTime+d);}
function shoot(){if(shot>0||reload||!ammo)return;ammo--;shot=.17;sfx(110,.1,.15);ray.setFromCamera(new THREE.Vector2(),camera);const roots=enemies.filter(e=>e.alive).map(e=>e.unit);const hit=ray.intersectObjects(roots,true)[0];if(hit){let n=hit.object;while(n.parent&&!enemies.some(e=>e.unit===n))n=n.parent;const e=enemies.find(q=>q.unit===n);if(e){e.hp-=50;sfx(220,.09,.04);if(e.hp<=0){e.alive=false;e.unit.visible=false;}}}const end=ray.ray.origin.clone().add(ray.ray.direction.multiplyScalar(35));trace(camera.position,end,'#f3dd78');}
function trace(a,b,c){const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints([a.clone(),b]),new THREE.LineBasicMaterial({color:c}));scene.add(l);traces.push({l,t:.07});}
function damage(n){let a=Math.min(armor,n*.7);armor-=a;hp-=n-a;sfx(75,.14,.09);if(hp<=0)finish(false);}
function update(dt){elapsed+=dt;shot-=dt;if(reload){reload-=dt;if(reload<=0){let n=Math.min(30-ammo,spare);ammo+=n;spare-=n}}let f=(keys.KeyW?1:0)-(keys.KeyS?1:0),s=(keys.KeyD?1:0)-(keys.KeyA?1:0);if(f||s){let l=Math.hypot(f,s),speed=(crouched?2.1:4.2)*dt;f/=l;s/=l;const fx=-Math.sin(yaw),fz=-Math.cos(yaw),rx=Math.cos(yaw),rz=-Math.sin(yaw),nx=camera.position.x+(fx*f+rx*s)*speed,nz=camera.position.z+(fz*f+rz*s)*speed;if(!collide(nx,camera.position.z))camera.position.x=nx;if(!collide(camera.position.x,nz))camera.position.z=nz}camera.position.y=terrainY(camera.position.x,camera.position.z)+(crouched?1.05:1.7);camera.rotation.set(pitch,yaw,0);for(const e of enemies)if(e.alive){const d=e.unit.position.distanceTo(camera.position);e.unit.lookAt(camera.position.x,e.unit.position.y,camera.position.z);if(d<38){e.cd-=dt;if(e.cd<0){e.cd=1+Math.random();if(Math.random()<(crouched?.35:.58)){damage(9+Math.random()*8);trace(e.unit.position,camera.position,'#e37a48')}}}}for(let i=traces.length-1;i>=0;i--){traces[i].t-=dt;if(traces[i].t<0){scene.remove(traces[i].l);traces.splice(i,1)}}const clear=enemies.length&&enemies.every(e=>!e.alive);if(clear)ui.objective.textContent='БЛОКПОСТ ЗАЧИЩЕН — ЗАЙМИТЕ РЕЛЕ';if(clear&&Math.hypot(camera.position.x-22,camera.position.z+18)<7)finish(true);hud();}
function drawMap(){map2d.fillStyle='#314a34';map2d.fillRect(0,0,150,150);map2d.fillStyle='#927a51';map2d.fillRect(72,0,8,150);map2d.fillStyle='#67685d';map2d.fillRect(82,62,20,15);map2d.fillStyle='#c7dc62';map2d.fillRect(87,67,6,6);for(const e of enemies)if(e.alive){map2d.fillStyle='#e05d4d';map2d.fillRect(75+e.unit.position.x*.7,75+e.unit.position.z*.7,5,5)}map2d.fillStyle='#f5f3d8';map2d.beginPath();map2d.arc(75+camera.position.x*.7,75+camera.position.z*.7,3.5,0,Math.PI*2);map2d.fill();map2d.strokeStyle='#fff';map2d.beginPath();map2d.moveTo(75+camera.position.x*.7,75+camera.position.z*.7);map2d.lineTo(75+camera.position.x*.7-Math.sin(yaw)*12,75+camera.position.z*.7-Math.cos(yaw)*12);map2d.stroke();}
function hud(){ui.health.style.width=Math.max(0,hp)+'%';ui.armor.style.width=Math.max(0,armor)+'%';ui.ammo.textContent=reload?'…':ammo;ui.stance.textContent=crouched?'● ПРИГНУВШИСЬ':'● СТОЯ';ui.clock.textContent=`06:${String(30+Math.floor(elapsed)%30).padStart(2,'0')}`;ui.squad.innerHTML=['СЕРЖАНТ ИЛЬИН','РЯДОВОЙ МОРО','МЕДИК ЛИ'].map(n=>`<div class="squad-member"><i></i>${n}</div>`).join('');drawMap();}
function finish(win){if(ended)return;ended=true;document.exitPointerLock();document.querySelector('#result').classList.remove('hidden');document.querySelector('#result-tag').textContent=win?'РЕЛЕ ЗАХВАЧЕНО':'ОТРЯД ПОТЕРЯЛ БОЙЦА';document.querySelector('#result-title').textContent=win?'ЗАДАЧА ВЫПОЛНЕНА':'ЗАДАНИЕ ПРОВАЛЕНО';document.querySelector('#result-copy').textContent=win?'Колонна пройдёт через перевал.':'Попробуйте снова, используя деревья и укрытия.';}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function togglePause(force){if(!started||ended)return;paused=force??!paused;document.querySelector('#pause').classList.toggle('hidden',!paused);if(paused)document.exitPointerLock();else canvas.requestPointerLock();}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Escape'){e.preventDefault();togglePause()}if(e.code==='KeyC'&&!paused)crouched=!crouched;if(e.code==='KeyR'&&!paused&&!reload&&ammo<30&&spare)reload=1.35});addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('mousedown',()=>{if(document.pointerLockElement!==canvas&&!paused)canvas.requestPointerLock();else if(!paused)shoot()});addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&started&&!paused){yaw-=e.movementX*.0024;pitch=Math.max(-1.05,Math.min(1.05,pitch-e.movementY*.0024))}});document.querySelector('#start').onclick=()=>{document.querySelector('#briefing').classList.add('hidden');started=true;startAudio();canvas.requestPointerLock();clock.start();animate()};document.querySelector('#resume').onclick=()=>togglePause(false);document.querySelector('#restart').onclick=()=>location.reload();
world();loadSoldier();camera.position.set(-48,terrainY(-48,46)+1.7,46);camera.lookAt(0,0,0);function animate(){let dt=Math.min(clock.getDelta(),.04);if(!ended&&!paused)update(dt);renderer.render(scene,camera);requestAnimationFrame(animate);}
